#!/usr/bin/env bash

sudo docker run --rm --name "origin" \
--privileged --pid=host --net=host \
-v /:/rootfs:ro \
-v /var/run:/var/run:rw \
-v /sys:/sys \
-v /sys/fs/cgroup:/sys/fs/cgroup:rw \
-v /var/log:/var/log \
-v /var/lib/docker:/var/lib/docker:rw \
-v /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes:rslave \
openshift/origin start